subtree:
  '@hamster-bot/constructeur':
    path: packages/constructeur
    url: https://github.com/AwesomeHamster/constructeur.git
  lodestone-news:
    path: packages/lodestone-news
    url: https://github.com/AwesomeHamster/lodestone-news.git
  koishi-plugin-ffxiv-eorzea:
    path: plugins/eorzea
    url: https://github.com/AwesomeHamster/koishi-plugin-ffxiv-eorzea.git
  koishi-plugin-hitokoto:
    path: plugins/hitokoto
    url: https://github.com/AwesomeHamster/koishi-plugin-hitokoto.git
  koishi-plugin-ffxiv-lodestone:
    path: plugins/lodestone
    url: https://github.com/AwesomeHamster/koishi-plugin-ffxiv-lodestone.git
  koishi-plugin-ffxiv-macrodict:
    path: plugins/macrodict
    url: https://github.com/AwesomeHamster/koishi-plugin-ffxiv-macrodict.git
