name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node: [14, 16]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Run tests
        run: |
          yarn test
        timeout-minutes: 10

  push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.HAMSTER_PAT }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config --global user.email "awesome.hamster.git@gmail.com"
          git config --global user.name "awesome-hamster-bot"

      - name: Install Dependencies
        run: |
          yarn install

      - name: Push subtrees to GitHub
        run: |
          node ./scripts/push.js
